# RECOVERED: partial depyo recovery; unresolved regions marked below
import time
from nicegui import ui
from src.route_manager import router
def create_auth_page():
    with ui.card().classes("w-full max-w-md mx-auto mt-8"):
        ui.label("License Activation").classes("text-xl mb-4")
        license_input = ui.input("Nhap license key").classes("w-full")
        if router.is_authenticated():
            ui.notify("Ban da duoc xac thuc!", type="positive")
            time.sleep(2)
            ui.navigate.to(router.start_path)
        else:
            ui.notify("Ban chua kich hoat hoac license da het han!", type="negative")
        def handle_auth():
            key = license_input.value; is_auth, msg = router.verify_activation_key(key)
            if is_auth:
                ui.notify(msg, type="positive")
                ui.navigate.to(router.start_path)
                return None
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            ui.notify(msg, type="negative")
        def clear_all_inputs():
            license_input.value = ""; ui.notify("Da xoa tat ca input", type="info")
        with ui.row().classes("w-full gap-2 mt-4"):
            ui.button("Kich hoat", on_click=handle_auth).classes("flex-1")
            ui.button("Xoa tat ca", on_click=clear_all_inputs).props("color=red").classes("flex-1")
